export const MAKE_REQUEST='MAKE_REQUEST'
export const FAIL_REQUEST='FAIL_REQUEST'
export const ADD_ROOM = 'ADD_ROOM'
export const GET_ROOM_TYPES = 'GET_ROOM_TYPES'
export const GET_ALL_ROOMS = 'GET_ALL_ROOMS'
export const GET_ROOM_OBJ = 'GET_ROOM_OBJ'
export const DELETE_ROOM = 'DELETE_ROOM'
export const UPDATE_ROOM = 'UPDATE_ROOM'
